services:
  - type: web
    name: inventory-system
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://inventory-system.onrender.com
      - key: PORT
        value: "8080"
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase: inventory-db
    postDeployCommand: php artisan migrate --force

databases:
  - name: inventory-db
    plan: free
